# These are supported funding model platforms

github: # Replace with your GitHub Sponsors username
# patreon: # Replace with your Patreon username
# ko_fi: # Replace with your Ko-fi username
# custom: # Replace with custom funding links



